package edwin.tou.ivvqlibrary.domain;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
public class Borrow {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    @Size(min = 13, max = 13)
    private String isbn13;

    @NotNull
    @ManyToOne
    private User borrower;

    @NotNull
    private LocalDateTime borrowDate;

    private LocalDateTime returnDate;

    public Borrow() {}

    public Borrow(String isbn13) {
        setIsbn13(isbn13);
    }

    public Borrow(String isbn13, User borrower) {
        this(isbn13);
        setBorrower(borrower);
    }

    public Borrow(String isbn13, User borrower, LocalDateTime date) {
        this(isbn13, borrower);
        setBorrowDate(date);
    }

    public Borrow(Long id, String isbn13, User borrower, LocalDateTime date) {
        this(isbn13, borrower, date);
        setId(id);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIsbn13() {
        return isbn13;
    }

    public void setIsbn13(String isbn13) {
        this.isbn13 = isbn13;
    }

    public User getBorrower() {
        return borrower;
    }

    public void setBorrower(User borrower) {
        this.borrower = borrower;
    }

    public LocalDateTime getBorrowDate() {
        return borrowDate;
    }

    public void setBorrowDate(LocalDateTime date) {
        this.borrowDate = date;
    }

    public LocalDateTime getReturnDate() {
        return returnDate;
    }

    public void setReturnDate(LocalDateTime returnDate) {
        this.returnDate = returnDate;
    }

    public void updateReturnDate() {
        setReturnDate(nowTruncatedToSeconds());
    }

    @PrePersist
    public void onPersistSetBorrowDateToNow() {
        setBorrowDate(nowTruncatedToSeconds());
    }

    private LocalDateTime nowTruncatedToSeconds() {
        return LocalDateTime
            .now(ZoneOffset.UTC)
            .truncatedTo(ChronoUnit.SECONDS);
    }

    @Override
    @Generated(reason = "Generated by IDE.")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result =
            prime * result + ((borrowDate == null) ? 0 : borrowDate.hashCode());
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((isbn13 == null) ? 0 : isbn13.hashCode());
        result =
            prime * result + ((borrower == null) ? 0 : borrower.hashCode());
        return result;
    }

    @Override
    @Generated(reason = "Generated by IDE.")
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Borrow other = (Borrow) obj;
        if (borrowDate == null) {
            if (other.borrowDate != null) return false;
        } else if (!borrowDate.equals(other.borrowDate)) return false;
        if (id == null) {
            if (other.id != null) return false;
        } else if (!id.equals(other.id)) return false;
        if (isbn13 == null) {
            if (other.isbn13 != null) return false;
        } else if (!isbn13.equals(other.isbn13)) return false;
        if (borrower == null) {
            if (other.borrower != null) return false;
        } else if (!borrower.equals(other.borrower)) return false;
        return true;
    }
}
