package edwin.tou.ivvqlibrary.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "library_user")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotBlank
    private String username;

    @NotNull
    @JsonIgnore
    private UUID apiKey;

    @JsonIgnore
    @OneToMany(mappedBy = "borrower")
    private List<Borrow> borrows;

    private boolean libraire;

    public User() {
        setBorrows(new ArrayList<>());
        setLibraire(false);
    }

    public User(@NotBlank String username, boolean libraire) {
        this(null, username, libraire);
    }

    public User(Long id, @NotBlank String username, boolean libraire) {
        this();
        this.id = id;
        this.username = username;
        this.libraire = libraire;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public UUID getApiKey() {
        return apiKey;
    }

    public void setApiKey(UUID apiKey) {
        this.apiKey = apiKey;
    }

    public void setLibraire(boolean libraire) {
        this.libraire = libraire;
    }

    public boolean isLibraire() {
        return libraire;
    }

    public List<Borrow> getBorrows() {
        return borrows;
    }

    public void setBorrows(List<Borrow> borrows) {
        this.borrows = borrows;
    }

    @PrePersist
    public void onPrePersistGenerateApiKey() {
        setApiKey(UUID.randomUUID());
    }

    @Override
    @Generated(reason = "Generated by IDE.")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((apiKey == null) ? 0 : apiKey.hashCode());
        result = prime * result + ((borrows == null) ? 0 : borrows.hashCode());
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + (libraire ? 1231 : 1237);
        result =
            prime * result + ((username == null) ? 0 : username.hashCode());
        return result;
    }

    @Override
    @Generated(reason = "Generated by IDE.")
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        User other = (User) obj;
        if (apiKey == null) {
            if (other.apiKey != null) return false;
        } else if (!apiKey.equals(other.apiKey)) return false;
        if (borrows == null) {
            if (other.borrows != null) return false;
        } else if (!borrows.equals(other.borrows)) return false;
        if (id == null) {
            if (other.id != null) return false;
        } else if (!id.equals(other.id)) return false;
        if (libraire != other.libraire) return false;
        if (username == null) {
            if (other.username != null) return false;
        } else if (!username.equals(other.username)) return false;
        return true;
    }
}
