package edwin.tou.ivvqlibrary;

import edwin.tou.ivvqlibrary.domain.Generated;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@Generated(
    reason = "Spring boot application class generated by spring initializr."
)
@SpringBootApplication
public class IvvqLibraryApplication {

    public static void main(String[] args) {
        SpringApplication.run(IvvqLibraryApplication.class, args);
    }
}
